GET http://localhost:5000/notes

###
GET http://localhost:5000/notes/18

###
POST http://localhost:5000/notes
Content-Type:  application/json

{
    "judul": "halo2",
    "konten": "yapping"
}

###
PATCH  http://localhost:5000/notes/21
Content-Type:  application/json

{
    "judul": "windah",
    "konten": "batubara"
}

###
DELETE http://localhost:5000/notes/2


###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiMUBnbWFpbC5jb20iLCJpYXQiOjE3NDc3MzA3NDUsImV4cCI6MTc0NzczMDc2MH0.pNOZFyAG1FiwWGkOLxWJUKhEJrVRgsycyUSFUCD4To4

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "windah123",
    "email": "123@gmail.com",
    "password": "batubara",
    "confPassword": "batubara"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "1@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
